/**
 * WARNING: DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated from sanitize.hpp.in via CMake.
 *
 * sanitize – filename and path sanitization with UTF-8 security checks
 * Version v2.0.0
 * Copyright 2026 John Erling Blad
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; only version 3 of the License applies.
 *
 * See accompanying file LICENSE or the page at https://www.gnu.org/licenses/
 **/

#pragma once

#define SANITIZE_VERSION_MAJOR 2
#define SANITIZE_VERSION_MINOR 0
#define SANITIZE_VERSION_PATCH 0
#define SANITIZE_VERSION "v2.0.0"

#include <concepts>
#include <cstddef>
#include <cstdint>
#include <format>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>

namespace sanitize {

/**
 * @brief Compile-time version constants, mirroring the SANITIZE_VERSION_*
 *        macros above for use in ordinary C++ code (template arguments,
 *        static_assert, runtime comparisons). The macros stay defined for
 *        callers who need #if-based version gating, which constexpr can't
 *        do.
 */
inline constexpr int VersionMajor = SANITIZE_VERSION_MAJOR;
inline constexpr int VersionMinor = SANITIZE_VERSION_MINOR;
inline constexpr int VersionPatch = SANITIZE_VERSION_PATCH;
inline constexpr std::string_view Version = SANITIZE_VERSION;

/**
 * @brief A compile-time string usable as a non-type template parameter.
 *
 * FixedString is a set, not a sequence: the constructor deduplicates, and
 * operator+/operator- give union/difference. Capacity is an upper bound
 * (deduced from the literal used to construct it); len is the actual
 * number of characters after construction/composition.
 *
 * @tparam Capacity Upper bound on the number of characters, deduced from
 *                   the array size of the literal passed to the
 * constructor.
 */
template <std::size_t Capacity>
struct FixedString {
    char data[Capacity]{};
    std::size_t len = 0;

    /** @brief Constructs an empty set (len == 0). */
    constexpr FixedString() = default;

    /**
     * @brief Constructs from a string literal, dropping duplicate
     * characters.
     *
     * Assumes str is a NUL-terminated string literal: the last array
     * element is treated as the terminator and not read as data. Passing
     * a non-literal char array of exact length silently drops its last
     * character.
     *
     * @param str The source literal; its array size determines Capacity.
     */
    explicit constexpr FixedString(const char (&str)[Capacity]) {
        for (std::size_t k = 0; k < Capacity - 1; ++k) {
            char c = str[k];
            if (!contains(c)) {
                data[len++] = c;
            }
        }
    }

    /**
     * @brief Checks whether a character is a member of this set.
     * @param c The character to look up.
     * @return true if c occurs in this FixedString.
     */
    [[nodiscard]] constexpr bool contains(char c) const {
        for (std::size_t i = 0; i < len; ++i) {
            if (data[i] == c) {
                return true;
            }
        }
        return false;
    }
};

/**
 * @brief Set union: characters of rhs not already in lhs are appended to
 * lhs.
 * @tparam N1 Capacity of the left-hand FixedString.
 * @tparam N2 Capacity of the right-hand FixedString.
 * @param lhs Left-hand operand.
 * @param rhs Right-hand operand.
 * @return A new FixedString containing every character in lhs or rhs, once
 * each.
 */
template <std::size_t N1, std::size_t N2>
constexpr auto operator+(
    const FixedString<N1>& lhs, const FixedString<N2>& rhs) {
    FixedString<N1 + N2> result;
    for (std::size_t k = 0; k < lhs.len; ++k) {
        result.data[result.len++] = lhs.data[k];
    }
    for (std::size_t k = 0; k < rhs.len; ++k) {
        if (!lhs.contains(rhs.data[k])) {
            result.data[result.len++] = rhs.data[k];
        }
    }
    return result;
}

/**
 * @brief Set difference: characters of lhs that also occur in rhs are
 * dropped.
 * @tparam N1 Capacity of the left-hand FixedString.
 * @tparam N2 Capacity of the right-hand FixedString.
 * @param lhs Left-hand operand.
 * @param rhs Right-hand operand.
 * @return A new FixedString containing every character in lhs that is not
 * in rhs.
 */
template <std::size_t N1, std::size_t N2>
constexpr auto operator-(
    const FixedString<N1>& lhs, const FixedString<N2>& rhs) {
    FixedString<N1> result;
    for (std::size_t k = 0; k < lhs.len; ++k) {
        if (!rhs.contains(lhs.data[k])) {
            result.data[result.len++] = lhs.data[k];
        }
    }
    return result;
}

/**
 * @brief Satisfied when every character in Chars is 7-bit ASCII (< 128).
 *
 * Config is only defined for character sets that satisfy this concept.
 * Sets containing characters above U+007F have no matching specialization
 * (a SIMD-based path is future work), so using one is a compile error.
 *
 * @tparam Chars The character set to check.
 */
template <FixedString Chars>
concept AsciiOnly = [] {
    for (std::size_t i = 0; i < Chars.len; ++i) {
        if (static_cast<unsigned char>(Chars.data[i]) >= 128) {
            return false;
        }
    }
    return true;
}();

namespace detail {

/**
 * @brief A 128-bit vector, hand-rolled instead of std::bitset because
 *        std::bitset's set()/test() are not constexpr until C++23.
 */
struct Bits128 {
    std::uint64_t lo = 0;
    std::uint64_t hi = 0;

    /**
     * @param pos Bit position to set.
     * @return true if pos was in [0, 128) and the bit was set; false if
     *         pos was out of range, in which case nothing was changed.
     */
    [[nodiscard]] constexpr bool set(unsigned char pos) {
        if (pos >= 128) {
            return false;
        }
        if (pos < 64) {
            lo |= (std::uint64_t{1} << pos);
        } else {
            hi |= (std::uint64_t{1} << (pos - 64));
        }
        return true;
    }

    /**
     * @param pos Bit position to test.
     * @return true if pos is in [0, 128) and the bit at pos is set; false
     *         if pos is out of range or the bit is unset.
     */
    [[nodiscard]] constexpr bool test(unsigned char pos) const {
        if (pos >= 128) {
            return false;
        }
        return pos < 64 ? ((lo >> pos) & 1u) != 0
                        : ((hi >> (pos - 64)) & 1u) != 0;
    }
};

}  // namespace detail

/**
 * @brief An immutable set of forbidden characters, built from a
 * compile-time FixedString. Membership testing is O(1) via a 128-bit
 * vector.
 *
 * No singleton: construct as many Config<Chars> instances as needed. Two
 * Config<Chars> instantiated from the same Chars are simply the same type.
 *
 * @tparam Chars The forbidden-character set. Must satisfy AsciiOnly.
 */
template <FixedString Chars>
class Config;

template <FixedString Chars>
    requires AsciiOnly<Chars>
class Config<Chars> {
   public:
    /** @brief Builds the forbidden-character bitset for Chars. */
    constexpr Config() : bits_(build()) {}

    /**
     * @param c The character to check.
     * @return true if c is a member of Chars.
     */
    [[nodiscard]] constexpr bool is_forbidden(char c) const noexcept {
        return static_cast<unsigned char>(c) < 128 &&
               bits_.test(static_cast<unsigned char>(c));
    }

   private:
    /**
     * @brief Sets one bit per character in Chars.
     * @return The resulting bitset.
     */
    static constexpr detail::Bits128 build() {
        detail::Bits128 b;
        for (std::size_t i = 0; i < Chars.len; ++i) {
            [[maybe_unused]] bool ok =
                b.set(static_cast<unsigned char>(Chars.data[i]));
        }
        return b;
    }

    detail::Bits128 bits_;
};

namespace detail {

/**
 * @brief Outcome of decoding one UTF-8 sequence.
 *
 * Valid: well-formed and not overlong. Invalid: empty, malformed, a
 * UTF-16 surrogate, or beyond U+10FFFF. Overlong: well-formed but encoded
 * with more bytes than necessary — see decode_utf8.
 */
enum class Utf8Status : std::uint8_t { Valid, Invalid, Overlong };

/** @brief Result of decode_utf8; see that function for field semantics. */
struct Utf8Decoded {
    Utf8Status status;
    int length;
    std::uint32_t codepoint;
};

/**
 * @brief Decodes one UTF-8 sequence starting at bytes.
 *
 * Overlong is reported with the correct structural byte length and the
 * true decoded codepoint (not just a failure code), so callers can either
 * skip the sequence or re-encode it canonically without redoing the
 * decode. A structurally well-formed sequence that decodes to a UTF-16
 * surrogate half (U+D800-U+DFFF) or beyond U+10FFFF is reported Invalid,
 * not Valid, since neither is a real Unicode codepoint.
 *
 * @param bytes The sequence's bytes; bytes[0] is the lead byte, and
 *              bytes.size() bounds how many continuation bytes are
 *              available. An empty bytes is reported as Invalid rather
 *              than being undefined behavior.
 * @return The decode result: status, byte length consumed, and codepoint
 *         (codepoint is only meaningful for Valid and Overlong; length is
 *         always meaningful and is 1 for Invalid, so callers can skip
 *         forward one byte and retry).
 */
// NOLINTNEXTLINE(readability-function-cognitive-complexity)
constexpr Utf8Decoded decode_utf8(std::span<const std::uint8_t> bytes) {
    if (bytes.empty()) {
        return {.status = Utf8Status::Invalid, .length = 1, .codepoint = 0};
    }
    std::uint8_t c = bytes[0];
    if (c < 0x80) {
        return {.status = Utf8Status::Valid, .length = 1, .codepoint = c};
    }
    if ((c & 0xE0) == 0xC0) {  // lead byte 110xxxxx: 2-byte sequence
        if (bytes.size() < 2 || (bytes[1] & 0xC0) != 0x80) {
            return {.status = Utf8Status::Invalid, .length = 1, .codepoint = 0};
        }
        // Lead byte's low 5 bits, then the continuation byte's low 6 bits.
        std::uint32_t codepoint =
            static_cast<std::uint32_t>((c & 0x1Fu) << 6) | (bytes[1] & 0x3Fu);
        if (codepoint < 0x80) {
            return {.status = Utf8Status::Overlong,
                    .length = 2,
                    .codepoint = codepoint};
        }
        return {.status = Utf8Status::Valid,
                .length = 2,
                .codepoint = codepoint};
    }
    if ((c & 0xF0) == 0xE0) {  // lead byte 1110xxxx: 3-byte sequence
        if (bytes.size() < 3 || (bytes[1] & 0xC0) != 0x80 ||
            (bytes[2] & 0xC0) != 0x80) {
            return {.status = Utf8Status::Invalid, .length = 1, .codepoint = 0};
        }
        std::uint32_t codepoint =
            static_cast<std::uint32_t>((c & 0x0Fu) << 12) |
            static_cast<std::uint32_t>((bytes[1] & 0x3Fu) << 6) |
            (bytes[2] & 0x3Fu);
        if (codepoint < 0x800) {
            return {.status = Utf8Status::Overlong,
                    .length = 3,
                    .codepoint = codepoint};
        }
        if (codepoint >= 0xD800 && codepoint <= 0xDFFF) {
            // UTF-16 surrogate half encoded as UTF-8: never a valid codepoint.
            return {.status = Utf8Status::Invalid, .length = 1, .codepoint = 0};
        }
        return {.status = Utf8Status::Valid,
                .length = 3,
                .codepoint = codepoint};
    }
    if ((c & 0xF8) == 0xF0) {  // lead byte 11110xxx: 4-byte sequence
        if (bytes.size() < 4 || (bytes[1] & 0xC0) != 0x80 ||
            (bytes[2] & 0xC0) != 0x80 || (bytes[3] & 0xC0) != 0x80) {
            return {.status = Utf8Status::Invalid, .length = 1, .codepoint = 0};
        }
        std::uint32_t codepoint =
            static_cast<std::uint32_t>((c & 0x07u) << 18) |
            static_cast<std::uint32_t>((bytes[1] & 0x3Fu) << 12) |
            static_cast<std::uint32_t>((bytes[2] & 0x3Fu) << 6) |
            (bytes[3] & 0x3Fu);
        if (codepoint >= 0xD800 && codepoint <= 0xDFFF) {
            // UTF-16 surrogate half: never a valid codepoint, regardless
            // of whether this 4-byte encoding of it is also overlong.
            return {.status = Utf8Status::Invalid, .length = 1, .codepoint = 0};
        }
        if (codepoint < 0x10000) {
            return {.status = Utf8Status::Overlong,
                    .length = 4,
                    .codepoint = codepoint};
        }
        if (codepoint > 0x10FFFF) {
            // Beyond the Unicode range: not a real codepoint.
            return {.status = Utf8Status::Invalid, .length = 1, .codepoint = 0};
        }
        return {.status = Utf8Status::Valid,
                .length = 4,
                .codepoint = codepoint};
    }
    return {.status = Utf8Status::Invalid, .length = 1, .codepoint = 0};
}

/**
 * @brief Encodes a codepoint as canonical (minimal-length) UTF-8.
 * @param codepoint The codepoint to encode.
 * @return The UTF-8 byte sequence for codepoint, 1 to 4 bytes long.
 */
inline std::string encode_utf8(std::uint32_t codepoint) {
    std::string result;
    if (codepoint < 0x80) {
        result += static_cast<char>(codepoint);
    } else if (codepoint < 0x800) {
        result += static_cast<char>(0xC0 | (codepoint >> 6));
        result += static_cast<char>(0x80 | (codepoint & 0x3F));
    } else if (codepoint < 0x10000) {
        result += static_cast<char>(0xE0 | (codepoint >> 12));
        result += static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F));
        result += static_cast<char>(0x80 | (codepoint & 0x3F));
    } else {
        result += static_cast<char>(0xF0 | (codepoint >> 18));
        result += static_cast<char>(0x80 | ((codepoint >> 12) & 0x3F));
        result += static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F));
        result += static_cast<char>(0x80 | (codepoint & 0x3F));
    }
    return result;
}

/**
 * @brief Renders a single already-forbidden character as its escape form.
 *
 * Named C escape (\\n, \\t, ...) for the eight control characters that
 * have one, \\xHH for any other control/DEL byte, and a plain backslash
 * prefix for anything else. Only called for characters already confirmed
 * forbidden by Config — escaping is never applied unconditionally.
 *
 * @param c The forbidden character to render.
 * @return The escaped form of c, 2 to 4 characters long.
 */
inline std::string escape_one(char c) {
    switch (c) {
        case '\0':
            return "\\0";
        case '\n':
            return "\\n";
        case '\r':
            return "\\r";
        case '\t':
            return "\\t";
        case '\v':
            return "\\v";
        case '\f':
            return "\\f";
        case '\b':
            return "\\b";
        case '\a':
            return "\\a";
        default:
            if (static_cast<unsigned char>(c) < 32 || c == 127) {
                return std::format("\\x{:02X}", static_cast<unsigned char>(c));
            }
            return std::string("\\") + c;
    }
}

/**
 * @brief Whether decoded's codepoint is itself forbidden by Chars.
 *
 * Shared by every caller that needs this check, regardless of decoded's
 * status: for a Valid single-byte result, codepoint < 128 exactly when
 * length == 1, so this doubles as the plain-ASCII check; for an Overlong
 * result it is the check that must run identically regardless of the
 * caller's Overlong policy. Config only knows how to test ASCII
 * characters, so anything else is never forbidden.
 *
 * @tparam Chars The forbidden-character set.
 * @param config A Config<Chars> instance to check against.
 * @param decoded A decode result from decode_utf8.
 * @return true if decoded's codepoint is a member of Chars.
 */
template <FixedString Chars>
[[nodiscard]] constexpr bool is_forbidden_codepoint(
    const Config<Chars>& config, const Utf8Decoded& decoded) {
    return decoded.codepoint < 128
        && config.is_forbidden(static_cast<char>(decoded.codepoint));
}

}  // namespace detail

/**
 * @brief Classification of one substring yielded by find_substrings.
 *
 * Overlong sequences are classified Forbidden if their decoded codepoint
 * is itself forbidden, and Invalid otherwise — an overlong encoding is
 * always structurally suspect, regardless of what it decodes to, so it
 * is never classified Valid.
 */
enum class FragmentType : std::uint8_t { Valid, Forbidden, Invalid };

/** @brief One run of consecutive characters sharing the same FragmentType. */
struct Fragment {
    FragmentType type;
    std::string_view text;
};

namespace detail {

/** @brief Result of classify_one: one character's type and byte length. */
struct ClassifiedChar {
    FragmentType type;
    std::size_t length;
};

/**
 * @brief Decodes and classifies the character starting at bytes[0].
 * @tparam Chars The forbidden-character set.
 * @param config A Config<Chars> instance to check against.
 * @param bytes The character's bytes; see decode_utf8 for how the span
 *              bounds the decode.
 * @return The character's FragmentType and its byte length.
 */
template <FixedString Chars>
[[nodiscard]] ClassifiedChar classify_one(
    const Config<Chars>& config, std::span<const std::uint8_t> bytes) {
    auto decoded = decode_utf8(bytes);
    auto length = static_cast<std::size_t>(decoded.length);

    if (decoded.status == Utf8Status::Invalid) {
        return {.type = FragmentType::Invalid, .length = length};
    }
    if (decoded.status == Utf8Status::Overlong) {
        bool forbidden = is_forbidden_codepoint<Chars>(config, decoded);
        return {
            .type = forbidden ? FragmentType::Forbidden : FragmentType::Invalid,
            .length = length};
    }
    if (is_forbidden_codepoint<Chars>(config, decoded)) {
        return {.type = FragmentType::Forbidden, .length = length};
    }
    return {.type = FragmentType::Valid, .length = length};
}

}  // namespace detail

/**
 * @brief A lazy, forward-only range over input, partitioned into
 *        consecutive runs of characters sharing the same FragmentType.
 *
 * Every byte of input is covered by exactly one yielded Fragment — this
 * is not limited to anomalies, it is the whole string, typed. Fragments
 * are std::string_view into input: valid as long as input stays valid
 * and unmodified. There is no write-back mechanism; a caller that wants
 * to fix Forbidden/Invalid runs builds a new string from the fragments
 * rather than editing input in place.
 *
 * @tparam Chars The forbidden-character set.
 */
template <FixedString Chars>
class SubstringRange {
public:
    /**
     * @brief Empty marker type; compares unequal to iterator until
     *        input is exhausted.
     */
    struct sentinel {};

    /** @brief Forward-only iterator yielding Fragment, one run at a time. */
    class iterator {
    public:
        using value_type = Fragment;

        /**
         * @brief Constructs an iterator and classifies the first run.
         * @param input The string being partitioned.
         * @param pos Byte offset to start classifying from.
         */
        iterator(std::string_view input, std::size_t pos)
            : input_(input), pos_(pos) {
            advance();
        }

        /** @return The Fragment for the run at the current position. */
        [[nodiscard]] Fragment operator*() const { return current_; }

        /** @brief Advances to the next run. @return *this. */
        iterator& operator++() {
            pos_ = end_;
            advance();
            return *this;
        }

        /**
         * @param terminator The end-of-range sentinel; carries no data,
         *                    present only so a range-based for loop can
         *                    compare against it.
         * @return true if the iterator hasn't reached the end of input.
         */
        bool operator!=([[maybe_unused]] sentinel terminator) const {
            return pos_ < input_.size();
        }

    private:
        /** @brief Classifies the run starting at pos_ into current_. */
        void advance() {
            if (pos_ >= input_.size()) {
                return;
            }
            static constexpr Config<Chars> config{};
            std::span<const std::uint8_t> bytes(
                reinterpret_cast<const std::uint8_t*>(input_.data()),
                input_.size());

            std::size_t i = pos_;
            auto first = detail::classify_one<Chars>(config, bytes.subspan(i));
            FragmentType type = first.type;
            i += first.length;

            while (i < input_.size()) {
                auto next =
                    detail::classify_one<Chars>(config, bytes.subspan(i));
                if (next.type != type) {
                    break;
                }
                i += next.length;
            }

            current_ = Fragment{.type = type,
                                 .text = input_.substr(pos_, i - pos_)};
            end_ = i;
        }

        std::string_view input_;
        std::size_t pos_;
        std::size_t end_ = 0;
        Fragment current_{};
    };

    /**
     * @param input The string to partition; not copied, must outlive
     *              the range.
     */
    explicit SubstringRange(std::string_view input) : input_(input) {}
    /** @return An iterator at the first run of input. */
    [[nodiscard]] iterator begin() const { return iterator(input_, 0); }
    /** @return The sentinel marking the end of input. */
    [[nodiscard]] sentinel end() const { return {}; }

private:
    std::string_view input_;
};

/**
 * @brief Partitions input into typed, run-length-grouped substrings.
 * @tparam Chars The forbidden-character set.
 * @param input The string to partition.
 * @return A lazy range of Fragment; iterate it with a range-based for loop.
 */
template <FixedString Chars>
[[nodiscard]] SubstringRange<Chars> find_substrings(std::string_view input) {
    return SubstringRange<Chars>(input);
}

/**
 * @brief Governs what happens to an overlong-encoded UTF-8 sequence whose
 *        decoded codepoint is not itself forbidden (the "harmless fluff"
 *        case).
 *
 * A forbidden character is always caught the same way regardless of this
 * policy, since detection runs against the decoded codepoint, never the
 * raw overlong bytes — this policy only decides what to do once that check
 * has already passed.
 *
 * - Throw:   reject the sequence outright.
 * - Remove:  drop the sequence from the output.
 * - Replace: substitute U+FFFD for the sequence.
 * - AsIs:    keep the original (overlong) bytes unchanged.
 * - Compact: re-encode the codepoint canonically (minimal length).
 */
enum class Overlong : std::uint8_t { Throw, Remove, Replace, AsIs, Compact };

/**
 * @brief A callable that turns one forbidden character into its
 * replacement text, for use with map.
 * @tparam Transform The callable type; must accept a char and return
 *                    something convertible to std::string.
 */
template <typename Transform>
concept CharTransform =
    std::invocable<Transform, char> &&
    std::convertible_to<std::invoke_result_t<Transform, char>, std::string>;

/**
 * @brief Applies transform to every character forbidden by Config<Chars>;
 *        every other character (including well-formed multi-byte UTF-8)
 *        passes through unchanged.
 *
 * replace, filter, and escape are all just this with a different
 * transform.
 *
 * @tparam Chars The forbidden-character set.
 * @tparam OverlongPolicy How to handle a harmless overlong-encoded
 * sequence; see Overlong. Defaults to Overlong::Throw.
 * @tparam Transform Deduced from the transform argument.
 * @param input The string to process.
 * @param transform Called with each forbidden character; its result is
 *                  appended to the output in place of that character.
 * @return The transformed copy of input.
 * @throws std::invalid_argument on invalid UTF-8, or on an overlong
 *         sequence when OverlongPolicy is Overlong::Throw.
 */
template <
    FixedString Chars,
    Overlong OverlongPolicy = Overlong::Throw,
    CharTransform Transform>
std::string map(std::string_view input, Transform transform) {
    static constexpr Config<Chars> config{};
    std::string result;
    result.reserve(input.size());

    std::span<const std::uint8_t> bytes(
        reinterpret_cast<const std::uint8_t*>(input.data()), input.size());
    std::size_t len = input.size();

    for (std::size_t i = 0; i < len;) {
        auto decoded = detail::decode_utf8(bytes.subspan(i));

        if (decoded.status == detail::Utf8Status::Invalid) {
            throw std::invalid_argument("Invalid UTF-8 sequence");
        }

        if (decoded.status == detail::Utf8Status::Overlong) {
            bool forbidden =
                detail::is_forbidden_codepoint<Chars>(config, decoded);
            if (forbidden) {
                result += transform(static_cast<char>(decoded.codepoint));
            } else if constexpr (OverlongPolicy == Overlong::Throw) {
                throw std::invalid_argument(
                    "Overlong UTF-8 encoding detected");
            } else if constexpr (OverlongPolicy == Overlong::Remove) {
                // drop
            } else if constexpr (OverlongPolicy == Overlong::Replace) {
                result += "\xEF\xBF\xBD";  // U+FFFD
            } else if constexpr (OverlongPolicy == Overlong::AsIs) {
                result.append(input.substr(
                    i, static_cast<std::size_t>(decoded.length)));
            } else if constexpr (OverlongPolicy == Overlong::Compact) {
                result += detail::encode_utf8(decoded.codepoint);
            }
            i += static_cast<std::size_t>(decoded.length);
            continue;
        }

        if (decoded.length == 1) {
            char c = static_cast<char>(decoded.codepoint);
            if (detail::is_forbidden_codepoint<Chars>(config, decoded)) {
                result += transform(c);  // NOLINT(build/include_what_you_use)
            } else {
                result += c;
            }
        } else {
            result.append(
                input.substr(i, static_cast<std::size_t>(decoded.length)));
        }
        i += static_cast<std::size_t>(decoded.length);
    }
    return result;
}

/**
 * @brief Replaces every forbidden character with a single fixed character.
 * @tparam Chars The forbidden-character set.
 * @tparam Replacement The character to substitute for each forbidden one.
 * @tparam OverlongPolicy How to handle a harmless overlong-encoded
 * sequence; see Overlong. Defaults to Overlong::Throw.
 * @param input The string to process.
 * @return The sanitized copy of input.
 * @throws std::invalid_argument on invalid UTF-8, or on an overlong
 *         sequence when OverlongPolicy is Overlong::Throw.
 */
template <
    FixedString Chars,
    char Replacement,
    Overlong OverlongPolicy = Overlong::Throw>
std::string replace(std::string_view input) {
    return map<Chars, OverlongPolicy>(
        input, [](char) { return std::string(1, Replacement); });
}

/**
 * @brief Same as replace, but drops forbidden characters instead of
 *        substituting one.
 * @tparam Chars The forbidden-character set.
 * @tparam OverlongPolicy How to handle a harmless overlong-encoded
 * sequence; see Overlong. Defaults to Overlong::Throw.
 * @param input The string to process.
 * @return The sanitized copy of input, with forbidden characters removed.
 * @throws std::invalid_argument on invalid UTF-8, or on an overlong
 *         sequence when OverlongPolicy is Overlong::Throw.
 */
template <FixedString Chars, Overlong OverlongPolicy = Overlong::Throw>
std::string filter(std::string_view input) {
    return map<Chars, OverlongPolicy>(
        input, [](char) { return std::string(); });
}

/**
 * @brief Backslash-escapes forbidden characters instead of replacing them.
 *
 * A small set of control characters get their named C escape (\\n, \\t,
 * ...), the rest of the control range gets \\xHH, and anything else
 * forbidden just gets a backslash prefix. Control characters are only
 * touched here if Chars actually includes them — see detail::escape_one.
 *
 * Caution: the output is only a safe, self-describing escaped string
 * (one where a reader can tell an escape sequence apart from a literal
 * backslash) if '\\' itself is a member of Chars. If it isn't, a literal
 * backslash in input passes through unescaped, and a downstream
 * un-escaper may misparse the boundary between it and whatever follows.
 * Include '\\' in Chars when the output needs to be safely un-escapable.
 *
 * @tparam Chars The forbidden-character set.
 * @tparam OverlongPolicy How to handle a harmless overlong-encoded
 * sequence; see Overlong. Defaults to Overlong::Throw.
 * @param input The string to process.
 * @return The escaped copy of input.
 * @throws std::invalid_argument on invalid UTF-8, or on an overlong
 *         sequence when OverlongPolicy is Overlong::Throw.
 */
template <FixedString Chars, Overlong OverlongPolicy = Overlong::Throw>
std::string escape(std::string_view input) {
    return map<Chars, OverlongPolicy>(
        input, [](char c) { return detail::escape_one(c); });
}

/**
 * @brief Inspects input character by character and throws on the first
 *        forbidden character or encoding problem.
 *
 * Never copies or transforms — use replace or filter for that.
 *
 * @tparam Chars The forbidden-character set.
 * @tparam OverlongPolicy How to handle a harmless overlong-encoded
 * sequence; see Overlong. Defaults to Overlong::Throw.
 * @param input The string to inspect.
 * @throws std::invalid_argument if input contains a forbidden character,
 *         invalid UTF-8, or (when OverlongPolicy is Overlong::Throw) an
 *         overlong sequence.
 */
template <FixedString Chars, Overlong OverlongPolicy = Overlong::Throw>
void strict(std::string_view input) {
    static constexpr Config<Chars> config{};
    std::span<const std::uint8_t> bytes(
        reinterpret_cast<const std::uint8_t*>(input.data()), input.size());
    std::size_t len = input.size();

    for (std::size_t i = 0; i < len;) {
        auto decoded = detail::decode_utf8(bytes.subspan(i));
        if (decoded.status == detail::Utf8Status::Invalid) {
            throw std::invalid_argument("Invalid UTF-8 sequence");
        }
        if (decoded.status == detail::Utf8Status::Overlong) {
            bool forbidden =
                detail::is_forbidden_codepoint<Chars>(config, decoded);
            if (forbidden) {
                throw std::invalid_argument("Forbidden character detected");
            }
            if constexpr (OverlongPolicy == Overlong::Throw) {
                throw std::invalid_argument(
                    "Overlong UTF-8 encoding detected");
            }
        } else if (detail::is_forbidden_codepoint<Chars>(config, decoded)) {
            throw std::invalid_argument("Forbidden character detected");
        }
        i += static_cast<std::size_t>(decoded.length);
    }
}

/**
 * @brief strict wrapped in a try-catch, for callers who'd rather have a
 * bool.
 *
 * Only catches std::invalid_argument, the one exception type strict
 * documents throwing. Anything else escaping strict is an unexpected
 * failure (e.g. std::bad_alloc) and is left to propagate rather than be
 * folded into "input is invalid" — since this function is noexcept, such
 * a failure terminates rather than being silently swallowed.
 *
 * @tparam Chars The forbidden-character set.
 * @tparam OverlongPolicy How to handle a harmless overlong-encoded
 * sequence; see Overlong. Defaults to Overlong::Throw.
 * @param input The string to inspect.
 * @return true if input is valid per Chars and OverlongPolicy, false
 * otherwise.
 */
template <FixedString Chars, Overlong OverlongPolicy = Overlong::Throw>
bool is_valid(std::string_view input) noexcept {
    try {
        strict<Chars, OverlongPolicy>(input);
        return true;
    } catch (const std::invalid_argument&) {
        return false;
    }
}

}  // namespace sanitize
